"""Common modules for scripts."""

from .config_utils import (
    categorize_time_horizon,
    find_dataset_by_id,
    find_preference_data_by_query_id,
    get_dataset_id_from_preference_data,
    get_expected_choice,
    get_time_ranges_from_dataset,
    load_dataset_config,
    resolve_dataset_config_from_query_id,
)
from .output_io import (
    load_dataset_output,
    load_preference_data,
    load_test_output,
    load_train_output,
    save_analysis_output,
    save_dataset,
    save_preference_data,
    save_probe_output,
    save_test_output,
    save_train_output,
)
from .schemas import (
    SCHEMA_VERSION,
    ChoiceModelConfig,
    DatasetOutput,
    DatasetOutputMetadata,
    EvaluationMetrics,
    GenerateDatasetOutput,
    InternalsReference,
    OptionOutput,
    PreferenceDataMetadata,
    PreferenceDataOutput,
    PreferenceDebugInfo,
    PreferenceItem,
    PreferencePairOutput,
    QuestionOutput,
    TestOutput,
    TrainOutput,
)
from .utils import (
    MODEL_QUIRKS,
    ModelQuirks,
    clear_memory,
    determine_choice,
    extract_flip_tokens,
    format_response_format,
    get_model_quirks,
    parse_label_from_response,
    strip_markdown,
    validate_no_unreplaced_placeholders,
)
from .prompt_builder import (
    build_prompt_from_question,
    build_time_horizon_marker_text,
)
from .verification import (
    CategoryStats,
    DataVerification,
    create_verification_plot,
    print_data_verification,
    serialize_verification,
    verify_data_alignment,
)
from .consistency import (
    ConsistencyAnalysis,
    ThetaConstraint,
    create_alignment_plot,
    create_ambiguous_analysis_plot,
    create_conflict_distribution_plot,
    create_conflicts_plot,
    create_consistency_plot,
    generate_alignment_analysis,
    generate_conflicts_analysis,
    print_consistency_analysis,
    serialize_consistency_analysis,
)
from .formatting_variation import (
    LABEL_STYLES,
    TIME_UNITS,
    FormattingVariation,
    apply_time_variation,
    convert_time_value,
    convert_to_random_unit,
    format_time_spelled,
    format_time_value,
    get_all_label_styles,
    get_random_labels,
    get_random_time_unit,
    get_sensible_units_for_time,
    spell_number,
)
from .token_positions import (
    ResolvedPosition,
    TokenSequenceInfo,
    find_text_in_tokens,
    parse_token_positions,
    resolve_all_positions,
    resolve_token_position,
)

__all__ = [
    # Config utils
    "categorize_time_horizon",
    "find_dataset_by_id",
    "find_preference_data_by_query_id",
    "get_dataset_id_from_preference_data",
    "get_expected_choice",
    "get_time_ranges_from_dataset",
    "load_dataset_config",
    "resolve_dataset_config_from_query_id",
    # I/O functions
    "load_dataset_output",
    "load_preference_data",
    "load_test_output",
    "load_train_output",
    "save_analysis_output",
    "save_dataset",
    "save_preference_data",
    "save_probe_output",
    "save_test_output",
    "save_train_output",
    # Schemas
    "SCHEMA_VERSION",
    "ChoiceModelConfig",
    "DatasetOutput",
    "DatasetOutputMetadata",
    "EvaluationMetrics",
    "GenerateDatasetOutput",
    "InternalsReference",
    "OptionOutput",
    "PreferenceDataMetadata",
    "PreferenceDataOutput",
    "PreferenceDebugInfo",
    "PreferenceItem",
    "PreferencePairOutput",
    "QuestionOutput",
    "TestOutput",
    "TrainOutput",
    # Utils
    "MODEL_QUIRKS",
    "ModelQuirks",
    "clear_memory",
    "determine_choice",
    "extract_flip_tokens",
    "format_response_format",
    "get_model_quirks",
    "parse_label_from_response",
    "strip_markdown",
    "validate_no_unreplaced_placeholders",
    # Prompt building
    "build_prompt_from_question",
    "build_time_horizon_marker_text",
    # Verification
    "CategoryStats",
    "DataVerification",
    "create_verification_plot",
    "print_data_verification",
    "serialize_verification",
    "verify_data_alignment",
    # Consistency analysis
    "ConsistencyAnalysis",
    "ThetaConstraint",
    "create_alignment_plot",
    "create_ambiguous_analysis_plot",
    "create_conflict_distribution_plot",
    "create_conflicts_plot",
    "create_consistency_plot",
    "generate_alignment_analysis",
    "generate_conflicts_analysis",
    "print_consistency_analysis",
    "serialize_consistency_analysis",
    # Formatting variations
    "LABEL_STYLES",
    "TIME_UNITS",
    "FormattingVariation",
    "apply_time_variation",
    "convert_time_value",
    "convert_to_random_unit",
    "format_time_spelled",
    "format_time_value",
    "get_all_label_styles",
    "get_random_labels",
    "get_random_time_unit",
    "get_sensible_units_for_time",
    "spell_number",
    # Token positions
    "ResolvedPosition",
    "TokenSequenceInfo",
    "find_text_in_tokens",
    "parse_token_positions",
    "resolve_all_positions",
    "resolve_token_position",
]
